"""Added products table

Revision ID: 256a425a84b2
Revises: e5534e9ee0a2
Create Date: 2022-05-10 22:38:46.612997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256a425a84b2'
down_revision = 'e5534e9ee0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, unique=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('stars', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )



def downgrade():
    op.drop_table('products')
